name: text_recognition
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  clipboard:
  cloud_firestore:
  firebase_ml_vision:
  flutter_tts:
  image_picker:
  translator:
  floating_action_bubble:
  percent_indicator:
  google_mobile_ads:
  provider:
  pedantic:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true































